version: "3.7"

services:
  web:
    image: momoirospanner/docker-nginx:1.17.5
    container_name: "web"
    ports:
      - "18080:80"
    volumes:
      - ./public:/var/www/html/public:cached
    restart: always

  app:
    image: momoirospanner/docker-php-fpm:7.3.11-dev
    container_name: "app"
    volumes:
      - .:/var/www/html/
      - vendor-cache:/var/www/html/vendor
      - /var/www/html/var/tmp
      - /var/www/html/.git
    links:
      - db
    depends_on:
      - db
    restart: always

  db:
    image: momoirospanner/docker-mysql:5.7.28
    container_name: "db"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - 13306:3306
    volumes:
      - mysql-db:/var/lib/mysql

  cache:
    image: redis:5.0.6-alpine
    container_name: "cache"
    restart: always
    ports:
      - 16379:6379
    volumes:
      - redis-cache:/data

volumes:
  vendor-cache:
    driver: local
  mysql-db:
    driver: local
  redis-cache:
    driver: local
